### PR TITLE
Add --password parameter to be used from command line

### PR DESCRIPTION
**Pull request by gpoul**

### CODE REVIEW

**Comment by ehuggett** [comment]
Thanks for doing this! 

(note: I did not consider the issue I'm about to raise when allowing the send URL, which includes the secretKey, to be specified on the CLI. I've opened #17 for that)

I have been very reluctant to allow the password to be specified on the CLI
- CLI arguments can be read by other processes e.g. from /proc/$pid/cmdline (normally world readable).
- It may be saved to the shells history file e.g. .bash_history (normally only readable by the user that owns it).
- Send URL's will eventually expire, but its very likely that a password will be reused (with Send or otherwise) so the risks of exposing it are longer lived.

The generic approaches to this problem that I am aware of are
- accept the password interactively (as currently done with getpass).
- accept the password from standard input (not ideal, at the moment send-cli will upload data from stdin and this seems more useful).
- read the password from a file and allow the filename to be specified on the CLI (awfully awkward if you never reuse a password).
- acknowledge that its a problem but reassure yourself that informing the user that its a bad idea excuses perpetuating bad practices :rofl:

Before merging your PR into master at the very least I want to print a warning about specifying the password on the CLI (only when present), Something along the lines of

```python
print('\033[1;41mWARNING\033[0m Passing secrets (URL or password) on the command line is STRONGLY DISCOURAGED, see the README for more information', file=sys.stderr)
```

Related/todo
- consider how this ties into #17 (can the same warning be used, etc)
- add a section to the README on the cmdline/shell history risks
- allow `--password` to be used when downloading a file
- To close #13 send-cli should not prompt for a password unless `--password` was specified without a value
- open an issue for reading the password from a file

I'm assuming none of this will interfere with the way you use send-cli? 

Let me know if you would be interested in doing any of it; I'm going to wait a day or so for any feedback you might have and then pull your PR into a new branch and adding commits for the changes I've outlined

Thanks again! (and sorry for the wall of text)

**Comment by gpoul** [comment]
So the main thing was that I wanted to run this as part of a CI build; I could also live with a change that would read this from an environment variable in case you're only concerned about command line parameters, but the thing is that the environment can be read as well; although it would solve your concerns regarding .bash_history and ps listings.

If we read this from an environment variable or file we will also need a parameter to specify that we explicitly don't want any password to be set in order to not get a prompt in this case either.

Would you think this is a better solution that could improve this pull request?

**Comment by ehuggett** [comment]
> So the main thing was that I wanted to run this as part of a CI build

Sounds interesting, if I had to guess your uploading generated data that you might want to inspect later (or may never want again)? If multiple people might want to get the file I would watch #8 

> I could also live with a change that would read this from an environment variable in case you're only concerned about command line parameters, but the thing is that the environment can be read as well; although it would solve your concerns regarding .bash_history and ps listings.

Yeah, equally problematic. 

> If we read this from an environment variable or file we will also need a parameter to specify that we explicitly don't want any password to be set in order to not get a prompt in this case either.

If I'm following would another workable option for you to be to use something like `[--password-unsafe PASSWORD]` for your PR, and (separately?) only prompt for a password if `[--password]` is used. This would ensure you are not prompted for a password and would instead receive an error if for some reason your CI script attempted to use a null password.

**Comment by gpoul** [comment]
@ehuggett I've updated this PR; let me know whether this matches what you suggested.

**Comment by ehuggett** [comment]
I see that the commit message has changed but the code seems the same? (I've done similar before; hopefully your changes are just uncommitted on your local branch!)

**Comment by gpoul** [comment]
@ehuggett now should be better.. sorry for that :)

**Comment by ehuggett** [comment]
cheers @gpoul 

I'll push this to PyPI within a few days

**Comment by gpoul** [comment]
tnx!

**Pull request merged**
